### ISSUE TITLE
In data table, display taxonomic distance column as human-readable strings

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#100]
The integers 0 ... are not meaningful to users. As we have discussed, this distance should instead be displayed in a meaningful way. For example,
- 0 --> species
- 1 --> genus
- 2 --> family
- 3 --> order 
- ...

**Comment by yosefdroth** [comment]
The reason why I left the taxonomic proximity as integers is so the user could distinguish between the relatedness of organisms within the same canonical rank (e.g. two organisms are in the same family, but one has a closer non-canonical rank). Do you think it's important to display the non-canonical differences anywhere?

**Comment by jonrkarr** [comment]
We've discussed this several times over months. The integers are not meaningful to users. This is why we have to provide more meaningful strings.

This can be dealt with a couple of ways
- The taxonomic filter could include intermediate unlabeled marks. To keep the labeled marks evenly spaced, the intermediate marks can be at non-integer values
- You could assign names to the intermediate ranks that have the name "no rank". Something like "sub-genus" (for 1 rank below genus), "sub-sub-genus" (for 2 ranks below genus), etc.

**Comment by yosefdroth** [comment]
The last time we discussed this, we planned on writing the name of the rank order in the taxonomix proximity column (e.g. domain, kingdom, phylum, etc.)

I realize now that this may not be possible to do, becuase the ranking of [species, genus, family, order, class, phylum, kingdom, domain], it itself not conssitent across organisms. 

For example:
escherichia coli has 7 canonical rankings- https://api.datanator.info/taxon/canon_rank_distance_by_name/?name=escherichia%20coli

homo sapiens has 8 - https://api.datanator.info/taxon/canon_rank_distance_by_name/?name=homo%20sapiens

and Trypanosoma cruzi has 5 - https://api.datanator.info/taxon/canon_rank_distance_by_name/?name=Trypanosoma%20cruzi

I propose that we add in the specific name rather than the rank order (e.g "escherichia" instead of "genus"). What do you all think?

**Comment by lzy7071** [comment]
Perhaps I'm missing something but why does the taxonomic filter bar need a fixed length? For any specific search input by the user, the target organism is a constant, which means the filter bar's length is already determined, i.e., if a user searches for organism `escherichia coli`, the filter bar will have a length of 7, on each dot of the bar there will be the name of the canonical rank; if a user searches for `homo sapiens`, the bar will have a length of 8.
I don't think skipping of canonical ranks for some species is problematic as `genus` means the same rank level across species. I presume some species doesn't have  a rank in `genus` probably because they can't be properly categorized at that level, which can be reflected at the filter bar.

**Comment by yosefdroth** [comment]
The filter bar is good as it is, I meant how we should fill out the taxonomic proximity column in the data table itself (right now it still has a number). 

We discusses that we could write "genus" instead of "Escherichia" in the data table. However, our API does not return what the rank-order of any of the names are (e.g. it does not say that Proteobacteria is a phylum). In theory, we could infer the rank order from the order of the names (e.g. the second name from the top is a kingdom). However, because this differs across organisms, there seems to be no way to infer what the rank order is to any name (e.g. there is no way to know that proteobacteria is a phylum, or that Kinetoplastea in trypansosoma is a class)

So maybe we should just write the name (e.g. proteobacteria), instead of the rank-order (e.g. phylum)

**Comment by lzy7071** [comment]
> The filter bar is good as it is, I meant how we should fill out the taxonomic proximity column in the data table itself (right now it still has a number).
> 
> We discusses that we could write "genus" instead of "Escherichia" in the data table. However, our API does not return what the rank-order of any of the names are (e.g. it does not say that Proteobacteria is a phylum). In theory, we could infer the rank order from the order of the names (e.g. the second name from the top is a kingdom). However, because this differs across organisms, there seems to be no way to infer what the rank order is to any name (e.g. there is no way to know that proteobacteria is a phylum, or that Kinetoplastea in trypansosoma is a class)
> 
> So maybe we should just write the name (e.g. proteobacteria), instead of the rank-order (e.g. phylum)

I'll include the rank names in the results.

**Comment by yosefdroth** [comment]
that would solve it -- thanks!. Can it be added to the protein groups as well

**Comment by lzy7071** [comment]
> that would solve it -- thanks!. Can it be added to the protein groups as well?

[api.datanator.info/taxon/canon_rank_distance_by_name/?](https://api.datanator.info/taxon/canon_rank_distance_by_name/?name=Trypanosoma%20cruzi) now gives you the rank name. 
Give me the endpoint to which you were referring.

**Comment by jonrkarr** [comment]
As Yang noted, we can use the subset of ranks that are applicable to each organism. We do not need to use the same number of ranks for each organism. The frontend gets this information from the REST API. It is not hard-coded into the frontend.

Yang, in advance by incorporating names of distances into the REST API.

**Comment by lzy7071** [comment]
> As Yang noted, we can use the subset of ranks that are applicable to each organism. We do not need to use the same number of ranks for each organism. The frontend gets this information from the REST API. It is not hard-coded into the frontend.
> 
> Yang, in advance by incorporating names of distances into the REST API.

Yup, the function has been added to [api.datanator.info/taxon/canon_rank_distance_by_name/?](https://api.datanator.info/taxon/canon_rank_distance_by_name/?name=Trypanosoma%20cruzi)

**Comment by yosefdroth** [comment]
done
