### ISSUE TITLE
Add buttons to export data in data tables

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_frontend#106]

**Comment by jonrkarr** [comment]
Add buttons above the table so the page looks like this

```
**Concentrations**                        CSV | JSON
--------------------------------------------------
|                                                |
|                                                |
|                                                |
|                                                |
--------------------------------------------------
```

The CSV button should use the AG-grid API to get the data formatted in CSV.

**Comment by jonrkarr** [comment]
Added DOM elements for buttons. Click action needs to be set to download data.

**Comment by jonrkarr** [comment]
Done.
- Removed unnecessary code
- Used preferred method of initiating JSON download -- click handler and blob
  - Instead of `DownloadLink` which generates a deprecation warning message because the javascript is embedded in the URL rather than attached to an event handler.
- Applied to all data pages
