### ISSUE TITLE
Fix implementation of onFilterChanged so that selection isn't lost when filters are changed

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#140]

**Comment by yosefdroth** [comment]
I have updated the pages so that the selections aren't lost. 

The reason why I implemented that way in the first place, is because of the following issue we now need to solve:

On the top of the grid, there is a selectAll/deselectAll checkbox. Right now, it's set to only work on filtered rows. This causes a problem in the following case:
 - user clicks selectAll
 - user filters out some rows
 - user hits deselectAll
Then the hidden rows won't be deselected. 

Alternatively, we could make the selectAll/deselectAll work on all rows (not just filtered). However, this would cause problems in the following scenario: 
 - if the user filters out some rows
 - user clicks selectAll box,
Then this would select all rows (not just the rows displayed). So there would be know way to selectAll of just the filtered rows without clicking on them one by one. 

The ideal behavior would be for the selectAll to be on just filtered, and the deselectAll to be for total. But I don't think AG grid has a way to do this: see Header Checkbox Selection - https://www.ag-grid.com/javascript-grid-selection. This is a particular problem for us if we expect users to frequently change the selections as they view the stats tool panel.

**Comment by jonrkarr** [comment]
The combination of filtering and selection can be implemented using `gridApi.forEachNodeAfterFilter` and filter for nodes with `selected=true`. 

Also, information about the filtered and selected data points can more easily be passed to the stats tool panel by registering event handlers to the grid within the stats tool panel. This avoids the need for redux. This is design can also support multiple data tables, which the current redux design cannot (easily).

I have implemented both of the above.
