### ISSUE TITLE
Fixing circleci errors for master branch

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#298]
How does one go about fixing the errors shown [here](https://app.circleci.com/pipelines/github/KarrLab/datanator_frontend/1384/workflows/d8683d4b-c5d9-4548-8c17-458741a73382/jobs/1453)? The reason the errors needed fixing is because:

- Netlify build was stopped so in order for updates to `master` to get deployed, `Auto Publishing` had to be turned on at Netlify.

- Production builds should only be deployed after tests are passed.

- If the errors persist, no new production builds will be deployed.

**Comment by jonrkarr** [comment]
One error is due to changes the I made to address Wolf's feedback. The second is due to timing of the response of the REST API. Both should be fixed.

**Comment by lzy7071** [comment]
It seems `build-third-party-license-report` is still causing an issue [here](https://app.circleci.com/pipelines/github/KarrLab/datanator_frontend/1391/workflows/e5886082-8810-454a-adc6-c0ff333c0336/jobs/1465)

**Comment by jonrkarr** [comment]
Its the dependency checking that failed. This should be fixed now. This is checking (a) all of the dependencies listed in package.json are used (i.e., imported somewhere) and (b) package.json lists all of the dependencies (everything that is imported at least once). For the most part, the dev dependencies need to be ignored by adding them to `.depcheckrc.yml` because they aren't imported.

FYI, the end of the testing step prints out a summary of the failures, e.g.
```
Build failed:
- Test for missing and unused dependencies failed
```

**Comment by lzy7071** [comment]
Great. Thank you for the information. I didn't know how to fix that particular dependency-related error. I've also been trying to figure out how to fix some cypress errors from integration tests. They seem to come and go.
