### ISSUE TITLE
[Airbrake] [Production] me(...).then(...).catch(...).finally is not a function

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#304]
**Airbrake error:** [#7421](https://karrlab.airbrake.io/projects/275996/groups/2779165249673217421)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` me(...).then(...).catch(...).finally is not a function ``
**Where:** `<no information>`
**Occurred at:** Jul 01, 2020 12:25:08 UTC
**First seen at:** Jul 01, 2020 12:25:08 UTC
**Occurrences:** 0 (0 since last deploy on Jun 29, 2020 21:06:11 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/search/unc-68/Caenorhabditis%20elegans/](https://datanator.info/search/unc-68/Caenorhabditis%20elegans/)
**File:** `/PROJECT_ROOT/static/js/main.148137e8.chunk.js`

**Backtrace:**
```
/PROJECT_ROOT/static/js/main.148137e8.chunk.js:1:in a.value
/PROJECT_ROOT/static/js/main.148137e8.chunk.js:1:in a.value
/PROJECT_ROOT/static/js/main.148137e8.chunk.js:1:in a.value
https://datanator.info/static/node_modules/react-dom/cjs/react-dom.production.min.js:212:in componentDidMount
```

**Comment by jonrkarr** [comment]
This is due to the user using an older, unsupported browser (Chrome 57.0.2987.98), that doesn't support `finally`.

This should have been caught by `src/scenes/UnsupportedBrowser/UnsupportedBrowser.js`. This defines v63 as the minimum supported version of Chrome (first version that supports finally).

I'll have to install Chrome 57 to why `UnsupportedBrowser.js` isn't catching the error.

**Comment by jonrkarr** [comment]
Done
