### ISSUE TITLE
[Airbrake] [Production] c.toLowerCase is not a function

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#333]
**Airbrake error:** [#7159](https://karrlab.airbrake.io/projects/275996/groups/2833861478730287159)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` c.toLowerCase is not a function ``
**Where:** `<no information>`
**Occurred at:** Sep 14, 2020 23:36:49 UTC
**First seen at:** Sep 14, 2020 23:36:49 UTC
**Occurrences:** 0 (0 since last deploy on Aug 19, 2020 19:03:09 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/search/WQZGKKKJIJFFOK-GASJEMHNSA-N/](https://datanator.info/search/WQZGKKKJIJFFOK-GASJEMHNSA-N/)
**File:** `https://datanator.info/static/js/scenes/SearchResults/GeneSearchResultsList.js`

**Backtrace:**
```
https://datanator.info/static/js/scenes/SearchResults/GeneSearchResultsList.js:45:in toLowerCase
https://datanator.info/static/js/scenes/SearchResults/SearchResultsList.js:93:in response
```

**Comment by jonrkarr** [comment]
This appears to have resulted from a change in the storage of data in the database. This was fixed by a5684a57c09194a004dc3bcaf8f45611f6a55d9f. I fixed this a little more robustly in e00f8d9ee2206699dec52ad01be07e32dbd72611 so that it works with both the old and new organization of data, in case our database is not internally consistent.
