### ISSUE TITLE
Improve responsiveness from intermediate page to category-specific page

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#64]
[Sample link (protein)](https://datanator.info/protein/ko/mol/?ko=K02502&organism=Escherichia%20coli)
[Sample link (reaction)](https://datanator.info/reaction/data/?substrates_inchi=ATP,Enzyme-Glutathione-Glutathionylspermidine%20complex&products_inchi=Enzyme-ATP-Glutathione-Glutathionylspermidine%20complex)
Issue is likely caused by a combination of round-about api calls and the performance of the underlying python queries.

**Comment by lzy7071** [comment]
[slow protein (975 ms)](/proteins/proximity_abundance/proximity_abundance_kegg/?kegg_id=K03696&anchor=Escherichia%20coli&distance=40&depth=40)
[slow rxn (1978 ms)](/reactions/kinlaw_by_name/?products=Enzyme-ATP-Glutathione-Glutathionylspermidine%20complex&substrates=ATP,Enzyme-Glutathione-Glutathionylspermidine%20complex&_from=0&size=1000&bound=tight)

**Comment by jonrkarr** [comment]
I'm marking this as "future", because I don't think this is a big problem. For an innovative academic tool, I think the responsiveness is pretty good.

The bottleneck is the REST calls. In my experience, the slowest call is the REST call which gets the UniProt ids for the proteins in the ortholog group. This is ~8s.

Many of the REST calls are retrieving more data than necessary for the pages. One potential way to reduce the latency is to implement more limited queries that only return the needed information. With the refactored code, it should be easier to understand what data actually needs to be returned.

**Comment by lzy7071** [comment]
> The bottleneck is the REST calls. In my experience, the slowest call is the REST call which gets the UniProt ids for the proteins in the ortholog group. This is ~8s.
> 

I think this would be a good starting point to try modularizing data retrieval and at the same time, avoiding problems with async from react.

**Comment by EricGT** [comment]
Since UniProt is released every 4 weeks and is a known fairly stable format, why not just download the file and parse into a means that can be queried locally? I know you are using REST, but [federated search](https://en.wikipedia.org/wiki/Federated_search) might be of value here.

In a proof of concept with UniProt I downloaded the file and parsed using Prolog DCGs. Granted the data as Prolog facts are rather large, but using Quick Load Files they load relatively fast. 

See: [Quick Load Files](https://swi-prolog.discourse.group/t/quick-load-files/1239/4)

While on the topic of federated search, Neo4j recently added that ability. See: [Extending the Graph Database with Data Federation](https://neo4j.com/blog/graph-database-data-federation/)

Not suggesting you change anything just dropping some ideas.

**Comment by jonrkarr** [comment]
The issue refers to two queries to our API which we should refactor. The data is downloaded and processed locally, in part for performance and in part because many of the data sources don't support federation.

**Comment by EricGT** [comment]
Thanks for the added info.

**Comment by jonrkarr** [comment]
I'm closing this because it seems to be working pretty well.
